# Menü címei
gui-title-player: "&8Referencia Páncélok"
gui-title-admin: "&cGUI Szerkesztő (Admin)"

# Üzenetek
msg-item-added: "&aSikeresen beállítva: &e%part% &a(Alap védelem: &f%level%&a)"
msg-error-special: "&cSpeciális szettet nem használhatsz referenciaként!"
msg-error-duplicate: "&cEbből a szettrészből már van egy a menüben!"
msg-no-permission: "&cNincs jogosultságod ehhez!"

# Fordítások a kijelzéshez
parts:
  _HELMET: "Sisak"
  _CHESTPLATE: "Mellvért"
  _LEGGINGS: "Nadrág"
  _BOOTS: "Csizma"

sets: {}
gui-layout: []
player-data: {}
