# SpecialArmor Configuration
# A szettek erejét a /setspecial parancs automatikusan ide menti.
sets: {}

# Itt tárolódik a GUI kinézete
gui-layout: []

# Itt tárolódnak a játékosok által betett tárgyak
player-data: {}
